### ISSUE TITLE
Multi languages

### ISSUE THREAD

**Issue by invaders-xx** [Codexshaper/laravel-woocommerce#18]
Hi,
First of all, many thanks for this very useful package.

I have a wordpress in 3 languages.

I was wondering how to handle the management of products translations (name, description, images). Do you have any idea how to handle that ?

Many thanks in advance,

David

**Comment by maab16** [comment]
Hello @invaders-xx 

Thanks for your comment. Unfortunately, I didn't find any doc in woocommerce official link but may I help you? Which multi-language plugin did you use?

Best regards,
Md Abu Ahsan Basir

**Comment by invaders-xx** [comment]
Many thanks for your feedback.

I use polylang.

**Comment by invaders-xx** [comment]
Could also be WPML : tell me which one is easier ?

**Comment by maab16** [comment]
I checked for polylang it gets all products with translated product.

![git poly lang](https://user-images.githubusercontent.com/20833514/80811142-1ab50a80-8be7-11ea-8186-e56a65938d17.png)

**Comment by invaders-xx** [comment]
Thanks for your feedback
