### ISSUE TITLE
Query orders

### ISSUE THREAD

**Issue by sytheveenje** [Codexshaper/laravel-woocommerce#2]
It would be cool if you could query the results like:

```php
$orders = Order::where('status', 'processing')->get();
```

**Comment by maab16** [comment]
Do you want custom query?

**Comment by maab16** [comment]
Hello @sytheveenje,

I added the same functionality that you want. Please try and inbox me if you need further help. Thanks
`$orders = Order::where('status', 'processing')->get();`
Or you can pass an array
`$orders = Order::where(['status' => 'processing'])->get();`

**Comment by Codexshaper** [comment]
@sytheveenje,

Thanks for your Post. You can get the same results easily. Follow below code
```
$orders = Order::all(['status' => 'processing']);
```

**Comment by sytheveenje** [comment]
I would like an Eloquent way to get the orders and products from WooCommerce. Now all you can do is:

```
$orders = Order::all();
```

This only returns 10 WooCommerce orders, but I want to go trough all and query them by status, date or maybe even by price, like this:

```
$orders = Order::where('status', 'processing')->get();

$orders = Order::where('total', '>', "100')->get();
```

**Comment by sytheveenje** [comment]
Thanks for your update! I tested with:
```
$orders = Order::where('status', 'processing')->get();
```

That didn't work, but this did work!
```
$orders = Order::all(['status' => 'processing']);
```

The only downside is that it only returns 10 results, but I got more then 10 processing orders.

**Comment by Codexshaper** [comment]
Thanks for your feedback.
I tested it's works fine for me.

```
$orders = Order::where('status', 'processing')->get();
```

check your version is latest version. The latest version is v1.1

I didn't check this code 
```
$orders = Order::where('total', '>', "100')->get();
```

**Comment by sytheveenje** [comment]
I have the latest version. But the query returns products, and products don't have status. So I get:

```
Automattic\WooCommerce\HttpClient\HttpClientException
Error: Invalid parameter(s): status [rest_invalid_param]
```

This is my query:

```
$orders = Order::where('status', 'processing')->get();
```

**Comment by sytheveenje** [comment]
Thanks for your replies!

I have the latests version and used your query. But then I get products with all status. Also status "publish".

I don't want products but Orders.

```
$orders = Order::where('status', 'processing')->get();
```

returns:

0 => {#386 ▼
    +"id": 24984
    +"name": "***"
    +"slug": "****"
    +"permalink": "****"
    +"date_created": "2019-02-14T10:30:37"
    +"date_created_gmt": "2019-02-14T09:30:37"
    +"date_modified": "2019-02-14T10:33:53"
    +"date_modified_gmt": "2019-02-14T09:33:53"
    +"type": "simple"
    +"status": "publish"
    +"featured": false
    +"catalog_visibility": "visible"
```

```
$orders = Order::where(['status' => 'processing'])->get();
```

returns:
````
Automattic\WooCommerce\HttpClient\HttpClientException
Error: Invalid parameter(s): status [rest_invalid_param]
````

**Comment by Codexshaper** [comment]
Thanks for information. Let me check. I'll update ASAP.

**Comment by maab16** [comment]
@sytheveenje

Thanks for your information. We fixed the issue in version v1.1.1. Please update the package and let us if you face same error again.

**Comment by sytheveenje** [comment]
It works, think I did not upgrade in the right way! 

Thank you for your patience and good work!

**Comment by Codexshaper** [comment]
If you like our support. Don't forget to press star button. Thanks

**Comment by maab16** [comment]
Good news,

Now you can use operators in where clause. Like

```
$orders = Order::where('total', '>', "100')->get();
```

You can also change the order

```
$orders = Order::where('total', '>', "100')->orderBy('id', 'asc')->get();
```
