### ISSUE TITLE
Get product's reviews

### ISSUE THREAD

**Issue by invaders-xx** [Codexshaper/laravel-woocommerce#27]
Dear @maab16 

According to the API document, I do the following command in order to get all the reviews for a specific product:
$reviews = Review::all(['product'=>[$id]]);

But I don't have any results event if I have a review in my database for the $id passed to the command.

FYI information, the review is not yet approved, Is there any restriction to list the on "hold" reviews ?

Many thanks in advance for your feedback.

**Comment by maab16** [comment]
@invaders-xx 

Thanks for creating an issue here. I checked it works fine. It's not API related issue. Check your WooCommerce settings. Go to WooCommerce/Settings/Products and check Review section. 

Thanks

**Comment by invaders-xx** [comment]
I checked and it seems to be ok : see screenshot
<img width="613" alt="image" src="https://user-images.githubusercontent.com/604907/81060553-fef58100-8ed2-11ea-982e-a8a8862c636a.png">

**Comment by invaders-xx** [comment]
It works but the API only get the approved comments. In my case I have 3 commments : 2 approved and one pending and only the 2 approved are listed in the API response

**Comment by invaders-xx** [comment]
Sorry my fault I forgot to mention "status=>"all" in the query as it's "approved by default"
