### ISSUE TITLE
Catching exceptions from the WooCommerce API

### ISSUE THREAD

**Issue by patricktsg** [Codexshaper/laravel-woocommerce#28]
How do I catch exceptions like this from the response in my API calls:

`"Error: Invalid ID. [woocommerce_rest_product_invalid_id]"`

Not sure how do do this with your traits

`$product = WooCommerce::find('products/'.$request->id);`

**Comment by maab16** [comment]
Hello @patricktsg 

Thanks for creating an issue. Do you mean you want to handle error? You can do it by try ... catch block.

```
try {
    $product = WooCommerce::find('products/'.$id);
    var_dump($product);
} catch (\Exception $e) {
    throw new \Exception("Sorry product not found. The error is " . $e->getMessage(), 1);
}
```

**Comment by patricktsg** [comment]
Thank you! That's great

**Comment by Codexshaper** [comment]
Sounds good. If you like this package then don't forget to press the star button that helps contributor to contribute more. If you have any other issue just close this one and add new one.

Thanks

**Comment by patricktsg** [comment]
No problem - starred!
