### ISSUE TITLE
Order Notes

### ISSUE THREAD

**Issue by sytheveenje** [Codexshaper/laravel-woocommerce#3]
Hi,

I saw in the Order Model that there is a possibility to add order notes (`createNote($orderId)`), how can I use this in my code?

Tried something like this, but that doesn't work:

```php
$WcOrder = WcOrder::create($data);

$note = [
      'author' => 'System',
      'note' => 'This order was created from order #' . $order->id
];

$WcOrder->createNote($note);
```

**Comment by maab16** [comment]
Please update latest version v1.1.7 (Fixed note issue) then run this query
```
       $order_id = 172;
       $note = [
          'author' => 'System',
          'note' => 'This order was created from order #' . $order_id 
        ];
        $createNote = Order::createNote($order_id, $note);
```

If you need further help please post your problem here. If it solved then leave us feedback and press the star button if you like our package.

Thanks

**Comment by sytheveenje** [comment]
Thanks a lot, will test this today!

**Comment by sytheveenje** [comment]
It works!
