### ISSUE TITLE
A Strange Problem

### ISSUE THREAD

**Issue by hqin2013** [Codexshaper/laravel-woocommerce#33]
Hey,@maab16

I ran into a strange question,hope you can help me out.

Use the below code to create a product, but always **create 2（even 3)  same products**.

`Product::create($data);`

The more strange is the newly created two products **have the same SKU**, which is disallowed by WooCommerce.

any suggestion?!

------------------------

PS1: I double product images make response change to slow, the product data contain more than 10 product images.

PS2: tried to change explorer to make sure the code executes only one time but failed.

------------------------

Thank you
Qin

**Comment by maab16** [comment]
Hello @hyn

Yea, It's really strange. Can you send your full code so that I can help you to solve this issue.

**Comment by hqin2013** [comment]
Hey,@maab16

The full source code is complex (for it use some third-platform data to generate product data). 

After many times try, I found the key problem is **images** fields --  if the products have many images, it will slow product creating and cause many same products, you can try it.

Regards 
Qin

**Comment by hqin2013** [comment]
Hey @maab16 
I think this is not your script problem. 

https://github.com/woocommerce/woocommerce-rest-api/issues/35
https://wordpress.org/support/topic/woocommerce-api-creates-duplicate-images/

Seems WooCommerce Team doesn't have the solution by now.


Regards
Qin
