### ISSUE TITLE
Using multiple connections

### ISSUE THREAD

**Issue by ianfortier** [Codexshaper/laravel-woocommerce#4]
Is it possible to pass the API keys directly from the controller to use differents WordPress connections without be required to edit the config?

Thanks

**Comment by maab16** [comment]
Hello @ianfortier

Thanks for your comment. You can set configuration in run time. Add below code in your controller method before the call
```
config([
    'woocommerce.store_url'       => 'YOUR_SITE_URL',
    'woocommerce.consumer_key'    => 'CONSUMER_KEY',
    'woocommerce.consumer_secret' => 'CONSUMER_SECRET',
]);
```
![config-in-runtime](https://user-images.githubusercontent.com/20833514/70451939-7cf25f00-1ad0-11ea-94b6-20584f562ac0.png)
