### ISSUE TITLE
Retrieve shipping_lines details from an order.

### ISSUE THREAD

**Issue by piloufaces** [Codexshaper/laravel-woocommerce#40]
Hello,

When I am searching a specific order, I retrieve all information but I cannot access to the shippings_lines details.
I am looking to retrieve.

Example from Request done on the Woocmmerce API using insomnia :

    "shipping_lines": [
      {
        "id": 13257,
        "method_id": "bpost_shipping",
        "method_title": "bpost - international",
        "total": "11.57"
      }

In the result in my application Laravel I have : 

    +"shipping_lines": array:1 [▼
      0 => {#324 …8}
    ]

How can I retrieve the details ?

Thanks

**Comment by maab16** [comment]
Hello @piloufaces,

Thanks for creating the issue. Did you setup shipping  lines? I tried it returns all the information that official doc has? Please check [official doc]( https://woocommerce.github.io/woocommerce-rest-api-docs/#retrieve-an-order) here.
