### ISSUE TITLE
Note class missing

### ISSUE THREAD

**Issue by piloufaces** [Codexshaper/laravel-woocommerce#42]
Hi, 
I am using the latest version and I need to retrieve the note of an order and it seems the Note class is missing....

Can you check ?

Thanks,

**Comment by maab16** [comment]
Hello @piloufaces,

Thanks for creating the issue. May you are trying Note facade. At this moment, there is no Facade for Note. From version 2.7 you can use Note Facade.

Make sure you are using version  2.7 or above. Reply with details if you still face same issue. If you have any other query then create a new issue.

**Comment by Codexshaper** [comment]
Issue solved.
