### ISSUE TITLE
JSON ERROR Syntax error

### ISSUE THREAD

**Issue by carlosromanxyz** [Codexshaper/laravel-woocommerce#6]
Hello

I'm working on local project using API from remote server, i followed your instructions but when i try to load `$orders = Order->all();` on my `Model`, i see `JSON ERROR: Syntax error`

My environment 

```
Laravel 6
PHP 7.2.9
Webserver nginx

```

**Comment by maab16** [comment]
Hello @carlosromanxyz,
Thanks for your comment. Can you send the details about error like a screenshot? You can send the example code that you tried so that I can find the error? You can send the code privately

-skype = maab.tips@gmail.com

Best regards,
Md Abu Ahsan Basir

**Comment by carlosromanxyz** [comment]
Hi

I sent you a email with screenshots, and my model code to get all orders is:

```
     /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $orders = Order::all();
        return view('event.create', compact('orders'));
    }
```
My website, CK, CS and WC API version was declared on .env, woocommerce config is untouched.

**Comment by maab16** [comment]
```
use Codexshaper\WooCommerce\Facades\Order;
Route::get('orders', function(){
    return Order::all();
});
```
Put the above code in your routes/web.php and inform me if what's result.

**Comment by carlosromanxyz** [comment]
Same error

In my model i've this declaration:

```
namespace App\Http\Controllers;

use App\Event;
use App\User;
use Auth;
use Codexshaper\WooCommerce\Facades\Order;
use Illuminate\Http\Request;
```

**Comment by maab16** [comment]
Did you check which API version you run on your project for eCommerce?  By default this package used v3. Can you check it? You can change the version from config/woocommerce.php

If you need remote help you can add me on 
skype (maab.tips@gmail.com) 
[Twitter](https://twitter.com/abuahsanbasir) 
[linkedin](https://www.linkedin.com/in/md-abu-ahsan-basir/)
 [Facebook](https://www.facebook.com/abuahsanbasir)

**Comment by carlosromanxyz** [comment]
Okay

I solve it running `php artisan config:cache` after reconfigure any line on .env file, please add this line on steps ;)

![fireshot](https://user-images.githubusercontent.com/20117120/73541328-ea57a780-4410-11ea-90e5-dac776e2f114.png)


Thank you

**Comment by maab16** [comment]
Sounds good. This is not this package related issue. Anyone should clear config, cache and restart the artisan after change the .env file.

**Comment by Codexshaper** [comment]
@carlosromanxyz 

We will add your `php artisan config:cache` soon our latest update.  BTW if you like this package you can press the star button to encourage contributor. You can put your suggestion if you want more feature that aren't available at this moment.

Good luck
