### ISSUE TITLE
Retrieve products from Orders

### ISSUE THREAD

**Issue by salahy** [Codexshaper/laravel-woocommerce#60]
Hello,
Can I retrieve list of products from orders with all information ?,
for example, I want to print all orders and under each order I want to list the products with the sku, image and other meta data.

I saw theres line_items but its not returning all the fields

Thanks

**Comment by maab16** [comment]
@salahy 

Thanks for creating another issue. At this moment there is no mapping relation with orders and products. You can do it manually. In later version I'll try to implement like below code

```
$order = Order::withProducts()->find(1);
```

That will add a products property as an array with product details.

Thanks

**Comment by salahy** [comment]
Thanks for the help :)
