### ISSUE TITLE
Filter by categories

### ISSUE THREAD

**Issue by salahy** [Codexshaper/laravel-woocommerce#61]
Hello,
The returned categories from the Product API are as json object
Can I filter products by category lets say Product::where("categories->name","clothes")->get(); ??
Thanks

**Comment by maab16** [comment]
@salahy 

Thanks for creating an issue. You can pass any parameter from https://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties

If you visit the [link](https://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties) then you can see a parameter name `category`. You can pass integer `category` id. For example fetch all products that has category id 7. Then code looks like

```
$products = Product::where('category', 7)->get();
```

If you have further query reply with details.

**Comment by salahy** [comment]
Thank you for the reply, Infact its not just category, I am trying to filter a json object, I have custom plugin to return an object and I want to filter that, to give you example, lets say I need to filter the store by name or id

<img width="267" alt="Screen Shot 2020-11-16 at 10 13 22 AM" src="https://user-images.githubusercontent.com/33222524/99227768-5cf51080-27f4-11eb-8908-7f1a7b80aeda.png">

is that possible, the native woocommerce api has default attributes and categories

Thanks again

**Comment by maab16** [comment]
By default there is no option to extra filter outside of https://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties. We can filter data only that are available in the above link. But you can do it by Laravel colelction filter because it returns laravel collection. Check this example is working or not.

```
// PHP version 7.4 or above
$products = Product::all()->filter( fn($product) => {
    // Apply your logic here
})

OR PHP version below 7.4
$products = Product::all()->filter(function($product) {
    // Apply your logic here
})
```

Thanks

**Comment by salahy** [comment]
Yes but its very bad approach when having too many products, anyway for the categories example you mentioned, the categories is an array not an object does the query work ?
<img width="657" alt="Screen Shot 2020-11-16 at 10 25 03 AM" src="https://user-images.githubusercontent.com/33222524/99228929-ff61c380-27f5-11eb-9463-8ad15849532c.png">

Thanks

**Comment by maab16** [comment]
I updated the link. Unfortunately there is no extra option here that we can search in deeper. Yes if there is lots of products then it may not good to use filter. You can use `withLazyCollection` to reduce memory.

```
$products = Product::withLazyCollection()->get()->filter(function($product) {
    // Apply your logic here
})
```

If you get any idea let me know I'll implement it ASAP. 

Thanks

**Comment by salahy** [comment]
Perfect, Thank you for the help
