### ISSUE TITLE
Is it compatible with WC4.0+

### ISSUE THREAD

**Issue by hqin2013** [Codexshaper/laravel-woocommerce#7]
Hi,

Does laravel-woocommerce compatible with woo-commerce 4.0+, i have tried it ,but found curl error.

Env:
`Laravel 6.X
PHP 7.3`

Best Regards

**Comment by maab16** [comment]
Hello @hqin2013,

Thanks for the message. It doesn't matter which woocommerce version. It's related to wocommerce API version. Current woccomerce latest API version is 3 so the default API version is 3. You can change the latest API version by changing the value of api_version from config/woocommerce.php. Or simply add WOOCOMMERCE_API_VERSION=v3 in your .env file.

Please read the official doc https://woocommerce.github.io/woocommerce-rest-api-docs/#introduction

If you face still error please reply with error or send me an email at codexshaper@gmail.com.

Best Regards,
Md Abu Ahsan Basir

**Comment by hqin2013** [comment]
Hey , Md

Thank you for your help.
I test again and get the error:

> Error: Sorry, you cannot list resources. [woocommerce_rest_cannot_view]

Found this ：

> The user you generated API keys for actually has access to those resources.

 in [here](https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API)

Is this the problem?!

Regards
Qin

**Comment by maab16** [comment]
@hqin2013 Thanks for your reply. I think it's not package related issue. I checked it old and new installation. Also, check-in HTTP and HTTPS. For HTTPS add WOOCOMMERCE_VERIFY_SSL=true. It works for every sector. I think you mistake when creating the API key. Please follow the original documentation and ensure bellow things

1. You are created REST API key
2. Permis both read and write permission
3. put correct WOOCOMMERCE_STORE_URL 
3. put correct WOOCOMMERCE_CONSUMER_KEY and WOOCOMMERCE_CONSUMER_SECRET
4. Optional. If your site is SSL protected (HTTPS) then add additional variable WOOCOMMERCE_VERIFY_SSL and set true as a value.

If not work try to a new Wordpress installation. If you still face the issue send your skype id at codexshaper@gmail.com

Best regards,
Md Abu Ahsan Basir

**Comment by hqin2013** [comment]
Hey, It's Okay now, Really Thank you！
