### ISSUE TITLE
I can't update a product? 

### ISSUE THREAD

**Issue by VGron** [Codexshaper/laravel-woocommerce#72]
I can't update or delete products only add. Do you know why? it break on ;

`     * @param string $endpoint API endpoint.

     * @param array  $data

     *

     * @return array

     */

    public function update($endpoint, $data)

    {

        try {

            self::__construct();

 

            return $this->client->put($endpoint, $data);

        } catch (\Exception $e) {

            throw new \Exception($e->getMessage(), 1);

        }

    }`

`Exception
Error: []`

**Comment by VGron** [comment]
Fixed, .htaccess issue.

**Comment by gusjara** [comment]
> Fixed, .htaccess issue.

How do you fixed with .htaccess?

Thank you!
