### ISSUE TITLE
Woocommerce Subscriptions

### ISSUE THREAD

**Issue by 4kasun** [Codexshaper/laravel-woocommerce#73]
Can we use this for woocommerce subscriptions or else custom endpoints? if so can someone provide a sample code?

**Comment by maab16** [comment]
Hi @4kasun,

Thanks for creating the issue. This package created based on woccommerce rest api. So only all functionality available that mentioned the doc. 

Here is the doc https://woocommerce.github.io/woocommerce-rest-api-docs/#introduction
