### ISSUE TITLE
how to Update a product variation?

### ISSUE THREAD

**Issue by hqin2013** [Codexshaper/laravel-woocommerce#9]
Hey,

I wanna update a product variation , is there any example code?
https://woocommerce.github.io/woocommerce-rest-api-docs/?php#update-a-product-variation

Regards
Qin

**Comment by maab16** [comment]
hello @hqin2013, Some functionality not working because I did the package for a sass project where Wooccomerce used for only simple products. For this reason, I didn't check product variation. I'll check asap and if it doesn't work then I'll fix it when I get time.

Best regards,
Md Abu Ahsan Basir

**Comment by maab16** [comment]
I'm reopening it because I release a new version where you can access everything that Woocommerce API provides.

After working the whole night I prepared it for you. Check and inform me. Make sure the version is greater than v2 or above.

Best regards,
Md Abu Ahsan Basir

**Comment by hqin2013** [comment]
Hey,Md

I tried Variation::batch() method, it works like a CHARM！
You saved me from operating database directly, Big Thank YOU!

Regards
Qin

**Comment by maab16** [comment]
It's my pleasure. Sounds really good.
