### ISSUE TITLE
 cURL Error: getaddrinfo() thread failed to start codexshaper/laravel-woocommerce

### ISSUE THREAD

**Issue by saqlainkhadim** [Codexshaper/laravel-woocommerce#95]
Hello @everyone  ,
i am facing issue related to **codexshaper/laravel-woocommerce** from long time. **When I update the product stock from laravel application to woocomerce application using codexshaper/laravel-woocommerce it gives this Error:**
 **cURL Error: getaddrinfo() thread failed to start** {"exception":"[object] (Exception(code: 1): cURL Error: getaddrinfo() thread failed to start at /home3/revebe57/public_html/carlanisa.revebe.com/vendor/codexshaper/laravel-woocommerce/src/Traits/WooCommerceTrait.php:83)

i don't know how to solve it.  if anyone has an idea about it then please tell me.
saqlainkhadimbusiness@gmail.com

**Comment by alexszilagyi** [comment]
Hi there,

Have you found a solution for this issue? Facing the same on:

```
        "codexshaper/laravel-woocommerce": "^3.0"
```
